apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: giteas.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Gitea
    listKind: GiteaList
    plural: giteas
    singular: gitea
  scope: Namespaced
  version: v1alpha1
