
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .GiteaAdminSecretName }}
  namespace: {{ .ApplicationNamespace }}
type: kubernetes.io/basic-auth
stringData:
  username: plotly
  password: {{ .GiteaAdminPassword }}
