kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .GiteaReposPvcName }}
  namespace: {{ .ApplicationNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .GiteaVolumeCapacity }}
