kind: Secret
apiVersion: v1
metadata:
  name: {{ .GiteaConfigName }}
  namespace: {{ .ApplicationNamespace }}
type: Opaque
# TODO enable back the memcach or at least re-evaluate it
stringData:
  app.ini: |
    APP_NAME = Dash Enterprise Git

    [cache]
    ADAPTER = memcache
    ENABLED = false
    HOST = gitea-memcached.{{ .ApplicationNamespace }}.svc.cluster.local:11211

    [database]
    DB_TYPE = postgres
    HOST    = {{ .GiteaPgServiceName }}.{{ .ApplicationNamespace }}.svc.cluster.local:5432
    NAME    = {{ .DatabaseName }}
    USER    = {{ .DatabaseUser }}
    PASSWD  = {{ .DatabasePassword }}

    [metrics]
    ENABLED = false

    [migrations]
    ALLOW_LOCAL_NETWORKS = true

    [repository]
    ROOT = /data/git/gitea-repositories

    [repository.upload]
    FILE_MAX_SIZE = 150

    [security]
    DISABLE_GIT_HOOKS = false
    INSTALL_LOCK = true

    [server]
    APP_DATA_PATH = /data
    DOMAIN = {{ .Hostname }}
    ENABLE_PPROF = false
    HTTP_PORT = 3000
    PROTOCOL = http
    ROOT_URL = http://{{ .Hostname }}
    SSH_DOMAIN = {{ .Hostname }}
    SSH_LISTEN_PORT = 2222
    SSH_PORT = 22
    START_SSH_SERVER = true

    [service]
    DISABLE_REGISTRATION = true
